---
name: Ansible

"on":
  pull_request:
    paths-ignore:
      - "ansible"

jobs:
  lint:
    name: Lint / Lint code
    runs-on: ubuntu-latest

    steps:
      - name: Skip check
        run: echo "No matching files - skipping check"
