---
name: JSON

"on":
  pull_request:
    paths-ignore:
      - "**.json"

jobs:
  style:
    name: Style / Check style
    runs-on: ubuntu-latest

    steps:
      - name: Skip check
        run: echo "No matching files - skipping check"
