---
name: Markdown

"on":
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  lint:
    name: Lint / Lint code
    runs-on: ubuntu-latest

    steps:
      - name: Skip check
        run: echo "No matching files - skipping check"

  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Skip check
        run: echo "No matching files - skipping check"
