---
name: Shell

"on":
  pull_request:
    paths-ignore:
      - "**.sh"

jobs:
  lint:
    name: Lint / Lint code
    runs-on: ubuntu-latest

    steps:
      - name: Skip check
        run: echo "No matching files - skipping check"

  style:
    name: Style / Check style
    runs-on: ubuntu-latest

    steps:
      - name: Skip check
        run: echo "No matching files - skipping check"
